### ISSUE TITLE
env_file release support

### ISSUE THREAD

**Issue by jtyler258** [deviceplane/deviceplane#10]
Currently only "environment" is supported in the release config for environment variables.
```
myService:
  image: foo
  environment:
    - API_KEY=supersecretsauce
```

Docker-compose v1+ supports an env_file option.
```
myService:
  image: foo
  env_file: /etc/foo/secrets.env
```

Because we do not want to put our secrets and third-party keys directly in the release config, a long-winded work around is currently required, which is not ideal.

**Comment by joshwget** [comment]
We do [interpolation on application configs from the CLI](https://deviceplane.com/docs/operating/cli/#environment-interpolation), so you could do something like this:

```
myService:
  image: foo
  environment:
    - API_KEY=$API_KEY
```

I still agree supporting `env_file` would be great though!
