### ISSUE TITLE
Add support for multiple registries

### ISSUE THREAD

**Issue by jtyler258** [deviceplane/deviceplane#12]
Following the docs [here](https://deviceplane.com/docs/deploying/private-image-repositories). I am able to use images hosted in our private GCR registry.

The problem is when public images are also needed.
For example I'm also using mosquitto and redis images in my release.
```YAML
redis:
  image: redis:alpine
  network_mode: "host"
mqtt-broker:
  image: eclipse-mosquitto
  network_mode: "host"
proprietary-service-1:
  image: gcr.io/****
  network_mode: "host"
proprietary-service-2:
  image: gcr.io/****
  network_mode: "host"
```

Because I have our private registry creds stored on the device, the agent tries to use them to pull from dockerhub, which fails.
`error pull image   error=Error response from daemon: Get https://registry-1.docker.io/v2/library/redis/manifests/alpine: unauthorized: incorrect username or password`

The current workaround is to just put the public images we need in our private registry.
This is not ideal since we don't get the regular updates of the publicly hosted versions.

The way docker generally handles this is to associate credentials to the corresponding registry domain. So being able to specify that in the /etc/deviceplane/registry_auth file might be a decent solution.
