### ISSUE TITLE
Bind Mount issue not indicated in console?

### ISSUE THREAD

**Issue by Humancell** [deviceplane/deviceplane#64]
I'm trying to launch a Node-RED container on a Raspberry Pi via DevicePlane.

My application is:
```
node-red:
 image: nodered/node-red:latest
 ports:
 - 1880:1880
 volumes:
 - /home/pi/node-red-data:/data
```
Watching on the Raspberry Pi (watch docker ps) the container is just endlessly restarting.  DevicePlane gives no status that I can find??

Is my use of "volumes" allowed?

How can I get some form of status via DevicePlane on what is going wrong?

What are you recommending as a way to debug something like this?
